name: Generate Snake Animation

on:
  # Jalankan secara otomatis setiap hari jam 00:00 UTC
  schedule:
    - cron: "0 0 * * *"
  
  # Atau jalankan manual
  workflow_dispatch:
  
  # Jalankan saat ada push ke branch main
  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Generate snake animation dari contribution graph
      - name: Generate snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.projectdanz }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      # Push hasil generate ke branch output
      - name: Push snake.svg to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
